micronaut:
  application:
    name: clean-arch
  security:
    enabled: false
    authentication: bearer
    token:
    jwt:
      enabled: true
      signatures:
        secret: "GkTjLJqkGxWYxTmI2U9mN7gczBL9G6tsU4ktvY7gXHY="
      claims-validators:
        roles:
          enabled: false
    intercept-url-map:
      - pattern: /auth/login
        http-method: POST
        access:
          - isAnonymous()


r2dbc:
  datasources:
    default:
      options:
        driver: pool
        protocol: postgres
        initialSize: 5
        maxSize: 35
        maxLifetime: PT280S
        maxIdleTime: PT240S
        maxAcquireTime: PT6S
        poolName: webcheckout-r2dbc

      url: ${DB_URL:`r2dbc:pool:postgresql://localhost:5432/postgres?stringtype=unspecified`}
      username: ${DB_USER:postgres}
      password: ${DB_PASSWORD:password123}
      schema-generate: CREATE
      dialect: POSTGRES


